version: 2

sources:
 - name: public
   database: citus
   schema: public

   tables:
   - name: movies
   - name: user_activity

models:
  - name: movie_popularity
    description: "Aggregated popularity stats for movies."
    columns:
      - name: movie_id
        tests:
          - unique
          - not_null
      - name: avg_rating
        tests:
          - not_null
          - accepted_values:
              values: [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]